
// Fetch character
export const FETCH_CHARACTER_REQUEST = 'FETCH_CHARACTER_REQUEST';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR';

// Fetch rival
export const FETCH_RIVAL_REQUEST = 'FETCH_RIVAL_REQUEST';
export const FETCH_RIVAL_SUCCESS = 'FETCH_RIVAL_SUCCESS';
export const FETCH_RIVAL_ERROR = 'FETCH_RIVAL_ERROR';
