
// Fetch character
export const FETCH_CHARACTER_FETCH = 'FETCH_CHARACTER_FETCH';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR';

// Fetch rival
export const FETCH_RIVAL_FETCH = 'FETCH_RIVAL_FETCH';
export const FETCH_RIVAL_SUCCESS = 'FETCH_RIVAL_SUCCESS';
export const FETCH_RIVAL_ERROR = 'FETCH_RIVAL_ERROR';
