// Fetch data

// Races
export const FETCH_RACES_REQUEST = 'FETCH_RACES_REQUEST';
export const FETCH_RACES_SUCCESS = 'FETCH_RACES_SUCCESS';
export const FETCH_RACES_ERROR = 'FETCH_RACES_ERROR';

// Classes
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

// Realms
export const FETCH_REALMS_REQUEST = 'FETCH_REALMS_REQUEST';
export const FETCH_REALMS_SUCCESS = 'FETCH_REALMS_SUCCESS';
export const FETCH_REALMS_ERROR = 'FETCH_REALMS_ERROR';

// Talents
export const FETCH_TALENTS_REQUEST = 'FETCH_TALENTS_REQUEST';
export const FETCH_TALENTS_SUCCESS = 'FETCH_TALENTS_SUCCESS';
export const FETCH_TALENTS_ERROR = 'FETCH_TALENTS_ERROR';

// Character related
export const FETCH_CHARACTER_REQUEST = 'FETCH_CHARACTER_REQUEST';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR';

export const SWITCH_CHARACTER = 'SWITCH_CHARACTER';
export const MOVE_CHARACTER = 'MOVE_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
